spring:
  datasource:
    password: 123456
    username: root
    url:  jdbc:mysql://127.0.0.1:3306/micro_service?characterEncoding=UTF-8
  jpa:
    show-sql: true
    database: mysql
server:
  port: 8888
